music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
	#/music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/music/album_id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #/music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    #/music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-edit'),

    #/music/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),


]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.FileField()


	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title
	

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
from .models import Album

class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/details.html'
	
class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')
	
			
						
		

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-7 col-sm-12">		
			<div class="panel panel-default">
				<div class="panel-body">
					
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{% include 'music/form-template.html' %}
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>	
					</form>
				</div>
			</div>	
		</div>		
	</div>

</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title%}PYTHON{% endblock %}</title>

<!-- Loads the path to your static files -->
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- Header -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'music:index' %}">Prabin</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
						Albums
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
						Songs
					</a>
				</li>
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" name="q" class="form-control" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>	
			</form>

			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'music:album-add' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
						Add Item
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
						Logout
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

{% block body%}
{% endblock %}

</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
<title>{% block title%}Album Details{% endblock %}</title>
 
{% block body %}
<div class="container-fluid">
	<div class="col-md-4">
		<img src="{{ album.album_logo.url }}">

		<h1>{{ album.album_title }}</h1>
		<h2>{{ album.artist }}</h2>

		{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
		{% endif %}

		{% for song in album.song_set.all %}
		<input type="radio" name="song" id="song{{ forloop.counter }}" value="{{ song.id }}" />
		<label for="song{{ forloop.counter }}">
			{{ song.song_title }}
			{% if song.is_favorite %}
				<img src="http://i.imgur.com/b9b13Rd.png" />
			{% endif %}		
		</label><br>
		{% endfor %}
</div>

	<div class="col-md-8">
		<a href="{% url 'music:index' %}">
			<button type="submit" class="btn btn-primary" name="submit">View All</button>
		</a>
		<h3>This is under construct</h3>
	</div>


{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
	<div class="col-sm-offset-2 sol-sm-10">
		<span class="text-danger small">{{ field.errors }}</span>
	</div>
	<label class="control-label col-sm-2">{{ field.label_tag }}</label>
	<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}	

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body%}
{% if all_albums %}
	<div class="container-fluid">
		{% for album in all_albums %}
			<div class="col-md-4">
				<div class="content-wrap">
					<img src="{{ album.album_logo.url }}"/><br>
					<h3>{{ album.album_title }}<br/></h3>
					<h4>{{ album.artist }}</h4>
				
					<a href="{% url 'music:detail' album.id %}">
						<button type="submit" class="btn btn-primary" name="submit">View Details</button>
					</a>
					<form action="{% url 'music:album-delete' album.id %}" method="post" style="display:inline">
						{% csrf_token %}
						<button type="submit" class="btn btn-danger" name="submit">Delete Item</button>
					</form>
					<a href="{% url 'music:album-edit' album.id %}">
						<button type="submit" class="btn btn-primary" name="submit">Edit</button>
					</a>
				</div>
			</div>
		{% endfor %}		
	</div>	
{% else %}
	<h3>You don't have any Albums</h3>
{% endif %}
</div>

{% endblock %}